// Versioned Allowlist Contract for Public Figures, Civic Entities, and Local Geo Aliases.
// Enforces EDITORIAL.md policy requirements for Tier A auto-publishing.

export const PUBLIC_FIGURE_ALLOWLIST: readonly string[] = [
	"Sonja Shaw",
	"Curt Marquez",
	"Eunice Ulloa",
	"Peter Rogers",
	"Art Bennett",
	"Brian Johsz",
	"Ray Marquez",
	"Cynthia Moran",
	"Karen Comstock",
	"Christopher Flores",
	"Marc Lucio",
	"Mark Hargrove",
	"Donald Bridge",
	"Andrew Cruz",
	"Jonathan Monroe",
	"James Na",
	"Norm Enfield",
	"Curt Hagman",
	"Shannon Dicus",
];

export const CIVIC_ENTITIES_ALLOWLIST: readonly string[] = [
	"Chino",
	"Chino Hills",
	"Chino Valley",
	"San Bernardino",
	"San Bernardino County",
	"Inland Empire",
	"Southern California",
	"California",
	"Ayala Park",
	"Ruben S. Ayala Park",
	"Prado Regional Park",
	"Prado Dam",
	"Chino Hills State Park",
	"English Springs Park",
	"The Shoppes at Chino Hills",
	"The Shoppes",
	"Chino Town Square",
	"Corner Bar",
	"Evergreen Devco",
	"7-Eleven",
	"Chino High School",
	"Don Antonio Lugo High School",
	"Don Lugo High School",
	"Don Lugo",
	"Ruben S. Ayala High School",
	"Ayala High School",
	"Chino Hills High School",
	"Boys Republic",
	"Boys & Girls Club",
	"Butterfield Ranch",
	"Butterfield Ranch Road",
	"Los Serranos",
	"Carbon Canyon",
	"Chino Airport",
	"Chino Valley Fire District",
	"CVUSD",
	"Chino Police Department",
	"Chino Hills Police Department",
	"Chino Planning Commission",
	"Chino Hills Planning Commission",
	"Chino City Council",
	"Chino Hills City Council",
	"Chino Valley Unified School District",
	"State Superintendent",
	"Planning Commission",
	"City Council",
	"School Board",
	"State of the City",
	"State of the District",
	"Central Avenue",
	"Schaefer Avenue",
	"Riverside Drive",
	"Edison Avenue",
	"Euclid Avenue",
	"Grand Avenue",
	"Peyton Drive",
	"Ramona Avenue",
	"Pipeline Avenue",
	"Monte Vista Avenue",
	"Mountain Avenue",
	"Philadelphia Street",
	"Francis Avenue",
	"Chino Corona Road",
];

export const LOCAL_GEO_ALIASES: readonly string[] = [
	"Chino",
	"Chino Hills",
	"CVUSD",
	"Chino Valley",
	"Chino Airport",
	"Prado",
	"Carbon Canyon",
	"Butterfield",
	"Los Serranos",
	"The Shoppes",
	"Ayala",
	"Don Lugo",
	"Chino High",
];

export const ADJACENT_CITIES: readonly string[] = [
	"Ontario",
	"Pomona",
	"Fontana",
	"Rancho Cucamonga",
	"Corona",
	"Upland",
	"Montclair",
	"Riverside",
];
